Encountered error C1083: Cannot open include file: 'winrt/Microsoft.UI.Dispatching.h': No such file or directory
Apparently:
When updating (winrt) from 0.8.0 preview to 0.8.0 there was a namespace change from Microsoft.System to Microsoft.UI.Dispatching and resume_foreground is now defined in Microsoft.UI.Dispatching.co_await.h.