Bump activesupport from 7.0.4.3 to 7.0.8 in /docs (#407)
Bumps [activesupport](https://github.com/rails/rails) from 7.0.4.3 to
7.0.8.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/releases">activesupport's
releases</a>.</em></p>
<blockquote>
<h2>7.0.8</h2>
<h2>Active Support</h2>
<ul>
<li>
<p>Fix <code>TimeWithZone</code> still using deprecated
<code>#to_s</code> when <code>ENV</code> or <code>config</code> to
disable it are set.</p>
<p><em>Hartley McGuire</em></p>
</li>
<li>
<p>Fix CacheStore#write_multi when using a distributed Redis cache with
a connection pool.</p>
<p>Fixes <a
href="https://redirect.github.com/rails/rails/issues/48938">#48938</a>.</p>
<p><em>Jonathan del Strother</em></p>
</li>
</ul>
<h2>Active Model</h2>
<ul>
<li>No changes.</li>
</ul>
<h2>Active Record</h2>
<ul>
<li>
<p>Fix <code>change_column</code> not setting <code>precision: 6</code>
on <code>datetime</code> columns when
using 7.0+ Migrations and SQLite.</p>
<p><em>Hartley McGuire</em></p>
</li>
<li>
<p>Fix unscope is not working in specific case</p>
<p>Before:</p>
<pre lang="ruby"><code>Post.where(id: 1...3).unscope(where: :id).to_sql
# &quot;SELECT `posts`.* FROM `posts` WHERE `posts`.`id` &gt;= 1 AND
`posts`.`id` &lt; 3&quot;
<p></code></pre></p>
<p>After:</p>
<pre lang="ruby"><code>Post.where(id: 1...3).unscope(where: :id).to_sql
# &quot;SELECT `posts`.* FROM `posts`&quot;
</code></pre>
<p>Fixes <a
href="https://redirect.github.com/rails/rails/issues/48094">#48094</a>.</p>
<p><em>Kazuya Hatanaka</em></p>
</li>
<li>
<p>Fix associations to a STI model including a <code>class_name</code>
parameter</p>
<pre lang="ruby"><code></code></pre>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/rails/rails/blob/v7.0.8/activesupport/CHANGELOG.md">activesupport's
changelog</a>.</em></p>
<blockquote>
<h2>Rails 7.0.8 (September 09, 2023)</h2>
<ul>
<li>
<p>Fix <code>TimeWithZone</code> still using deprecated
<code>#to_s</code> when <code>ENV</code> or <code>config</code> to
disable it are set.</p>
<p><em>Hartley McGuire</em></p>
</li>
<li>
<p>Fix CacheStore#write_multi when using a distributed Redis cache with
a connection pool.</p>
<p>Fixes <a
href="https://redirect.github.com/rails/rails/issues/48938">#48938</a>.</p>
<p><em>Jonathan del Strother</em></p>
</li>
</ul>
<h2>Rails 7.0.7.2 (August 22, 2023)</h2>
<ul>
<li>No changes.</li>
</ul>
<h2>Rails 7.0.7.1 (August 22, 2023)</h2>
<ul>
<li>
<p>Use a temporary file for storing unencrypted files while editing</p>
<p>[CVE-2023-38037]</p>
</li>
</ul>
<h2>Rails 7.0.7 (August 09, 2023)</h2>
<ul>
<li>
<p>Fix <code>Cache::NullStore</code> with local caching for repeated
reads.</p>
<p><em>fatkodima</em></p>
</li>
<li>
<p>Fix <code>to_s</code> with no arguments not respecting custom
<code>:default</code> formats</p>
<p><em>Hartley McGuire</em></p>
</li>
<li>
<p>Fix <code>ActiveSupport::Inflector.humanize(nil)</code> raising
<code>NoMethodError: undefined method `end_with?' for
nil:NilClass</code>.</p>
<p><em>James Robinson</em></p>
</li>
<li>
<p>Fix <code>Enumerable#sum</code> for <code>Enumerator#lazy</code>.</p>
<p><em>fatkodima</em>, <em>Matthew Draper</em>, <em>Jonathan
Hefner</em></p>
</li>
<li>
<p>Improve error message when EventedFileUpdateChecker is used without a
compatible version of the Listen gem</p>
<p><em>Hartley McGuire</em></p>
</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rails/rails/commit/fc734f28e65ef8829a1a939ee6702c1f349a1d5a"><code>fc734f2</code></a>
Preparing for 7.0.8 release</li>
<li><a
href="https://github.com/rails/rails/commit/7bf0e439da8d089a22ea5d144373435eed15ba96"><code>7bf0e43</code></a>
Fix TimeWithZone#to_s being overriden with ENV set</li>
<li><a
href="https://github.com/rails/rails/commit/f5fd433b6dfb56f01c0da18dfab359f3184bf3b8"><code>f5fd433</code></a>
Document how to remove to_s deprecation warnings when defaul format is
changed</li>
<li><a
href="https://github.com/rails/rails/commit/ed9f2920433f928d1f3aff7075fb86612d855441"><code>ed9f292</code></a>
Merge tag 'v7.0.7.2' into 7-0-stable</li>
<li><a
href="https://github.com/rails/rails/commit/3668b4b5978822f1e6311c7fd7a32f58daee136a"><code>3668b4b</code></a>
Preparing for 7.0.7.2 release</li>
<li><a
href="https://github.com/rails/rails/commit/2294b8b27a95f12bb25a891d1ce8f3f68c6af601"><code>2294b8b</code></a>
Bumping version</li>
<li><a
href="https://github.com/rails/rails/commit/2766c93b5c671f44433a63e84c7de33b74f0c3ac"><code>2766c93</code></a>
Merge branch '7-0-sec' into 7-0-stable</li>
<li><a
href="https://github.com/rails/rails/commit/c92caefc2bdf856845a72b8608d5603b330e8c3e"><code>c92caef</code></a>
Preparing for 7.0.7.1 release</li>
<li><a
href="https://github.com/rails/rails/commit/936587d49b3d490462c794b30fb672cef43e1bd0"><code>936587d</code></a>
updating version / changelog</li>
<li><a
href="https://github.com/rails/rails/commit/a21d6edf35a60383dfa6c4da49e4b1aef5f00731"><code>a21d6ed</code></a>
Use a temporary file for storing unencrypted files while editing</li>
<li>Additional commits viewable in <a
href="https://github.com/rails/rails/compare/v7.0.4.3...v7.0.8">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=activesupport&package-manager=bundler&previous-version=7.0.4.3&new-version=7.0.8)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)
You can disable automated security fix PRs for this repo from the
[Security Alerts
page](https://github.com/OpenKneeboard/OpenKneeboard/network/alerts).

</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>